# Generated by Django 4.2.3 on 2023-08-13 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_user_following_delete_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_posts',
            field=models.ManyToManyField(blank=True, related_name='users_who_liked', to='network.post'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
